import { describe, expect, it } from "vitest";
import {
  JavaRandom,
  deriveNodeSeed,
  javaStringHashCode,
} from "@/utils/density/javaRandom";

/**
 * Ground truth for this file was generated by running java.util.Random and
 * String.hashCode on a real JDK (Temurin 26.0.1), not reproduced from memory:
 *
 *   for (long s : seeds) { Random r = new Random(s); r.nextInt(); ... }
 *
 * JavaRandom underpins every seed the worldgen parity work depends on. The
 * parity harnesses exercise it only indirectly, so a subtle error here would
 * surface as "our noise doesn't match Hytale" far from its actual cause — and
 * every captured fixture would need regenerating. These assertions pin the RNG
 * itself.
 */

const NEXT_INT: Record<string, number[]> = {
  "0": [-1155484576, -723955400, 1033096058, -1690734402, -1557280266],
  "1": [-1155869325, 431529176, 1761283695, 1749940626, 892128508],
  "42": [-1170105035, 234785527, -1360544799, 205897768, 1325939940],
  "-1": [1155099827, 1887904451, 52699159, -1941176418, -1451336087],
  "123456789": [-1442945365, -1016548095, 1962592967, 1094656688, 1677212580],
};

const NEXT_DOUBLE: Record<string, number[]> = {
  "0": [0.730967787376657, 0.24053641567148587, 0.6374174253501083],
  "1": [0.7308781907032909, 0.41008081149220166, 0.20771484130971707],
  "42": [0.7275636800328681, 0.6832234717598454, 0.30871945533265976],
  "-1": [0.26894263088050496, 0.012269981921235296, 0.6620844841121951],
  "123456789": [0.664038103272266, 0.45695178590520646, 0.39050647939140426],
};

describe("JavaRandom matches java.util.Random", () => {
  for (const [seed, expected] of Object.entries(NEXT_INT)) {
    it(`nextInt() sequence for seed ${seed}`, () => {
      const rng = new JavaRandom(Number(seed));
      expect(expected.map(() => rng.nextInt())).toEqual(expected);
    });
  }

  for (const [seed, expected] of Object.entries(NEXT_DOUBLE)) {
    it(`nextDouble() sequence for seed ${seed}`, () => {
      const rng = new JavaRandom(Number(seed));
      // Exact equality: nextDouble is constructed to stay under 2^53, so it is
      // representable in a float64 with no rounding. Anything less than exact
      // would mean the port has drifted.
      expect(expected.map(() => rng.nextDouble())).toEqual(expected);
    });
  }

  it("accepts a bigint seed identically to the number form", () => {
    const a = new JavaRandom(42);
    const b = new JavaRandom(42n);
    expect(a.nextInt()).toBe(b.nextInt());
  });

  it("keeps nextDouble in [0, 1)", () => {
    const rng = new JavaRandom(987654321);
    for (let i = 0; i < 500; i++) {
      const v = rng.nextDouble();
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(1);
    }
  });

  it("produces a distinct stream per seed", () => {
    const a = new JavaRandom(1).nextInt();
    const b = new JavaRandom(2).nextInt();
    expect(a).not.toBe(b);
  });
});

describe("javaStringHashCode matches String.hashCode", () => {
  const CASES: Array<[string, number]> = [
    ["", 0],
    ["a", 97],
    ["hello", 99162322],
    ["Hytale", -2118369961],
    ["World-River-Map", 912309568],
  ];

  for (const [input, expected] of CASES) {
    it(`"${input}" → ${expected}`, () => {
      expect(javaStringHashCode(input)).toBe(expected);
    });
  }

  it("reproduces Java's classic Aa/BB collision", () => {
    // Not a curiosity: it proves the 31*h + c accumulation wraps at 32 bits the
    // way Java's does, rather than being merely "a hash".
    expect(javaStringHashCode("Aa")).toBe(2112);
    expect(javaStringHashCode("BB")).toBe(2112);
  });

  it("stays within signed 32-bit range for long inputs", () => {
    const h = javaStringHashCode("x".repeat(10_000));
    expect(Number.isInteger(h)).toBe(true);
    expect(h).toBeGreaterThanOrEqual(-(2 ** 31));
    expect(h).toBeLessThan(2 ** 31);
  });
});

describe("deriveNodeSeed", () => {
  it("is deterministic for the same key chain", () => {
    expect(deriveNodeSeed("biome", "density", "a")).toBe(deriveNodeSeed("biome", "density", "a"));
  });

  it("depends on the order of the key chain", () => {
    expect(deriveNodeSeed("a", "b")).not.toBe(deriveNodeSeed("b", "a"));
  });

  it("joins the key chain without a separator, matching Hytale", () => {
    // Chains that concatenate to the same string DO collide, by design:
    // deriveNodeSeed joins with "" because that is what the real generator
    // does — noiseDefaultsParity asserts deriveNodeSeed("MyWorldSeed",
    // "Skyreach_Base_Density") equals the single concatenated key. Introducing
    // a separator to avoid this collision would silently break seed parity with
    // the game, so the collision is pinned here rather than treated as a bug.
    expect(deriveNodeSeed("ab", "c")).toBe(deriveNodeSeed("a", "bc"));
    expect(deriveNodeSeed("ab", "c")).toBe(deriveNodeSeed("abc"));
  });
});
