/**
 * Ground-truth terrain parity: compare a chunk the game actually generated
 * against what TerraNova's density evaluator produces for the same coordinates.
 *
 * Node-level parity fixtures (src/utils/density/__tests__) prove each noise
 * primitive matches the V2 jar. They cannot prove the *assembled* graph does —
 * correct primitives wired together wrongly still produce wrong terrain. This
 * closes that gap end to end.
 *
 * Deliberately compares solidity only, never block materials: solid/air needs
 * no palette mapping, so every reported difference is a real parity bug rather
 * than a gap in a lookup table. That keeps the number trustworthy.
 *
 * Also deliberately bypasses `voxelExtractor`: that path median-filters the
 * heightmap for display, and diffing smoothed output against the game would
 * measure our own smoothing instead of parity.
 */

import type { ChunkDataResponse } from "@/utils/ipc";
import { SOLID_THRESHOLD } from "@/utils/voxelExtractor";

/** Block id used for empty space in the sidecar's chunk encoding. */
const AIR_BLOCK_ID = 0;

export interface ParityDivergence {
  x: number;
  y: number;
  z: number;
  /** What the game has here. */
  game: "solid" | "air";
  /** What our evaluator produced. */
  local: "solid" | "air";
  density: number;
}

export interface ChunkParityResult {
  comparable: boolean;
  /** Present when `comparable` is false: why this chunk cannot be judged. */
  reason?: string;
  chunkX: number;
  chunkZ: number;
  totalVoxels: number;
  mismatches: number;
  /** 0..1. `1` means every sampled voxel agreed. */
  matchRatio: number;
  /** Solid locally, air in game — terrain we invent. */
  extraSolid: number;
  /** Air locally, solid in game — terrain we miss. */
  extraAir: number;
  /**
   * Lowest-Y disagreement. Divergence propagates upward, so the lowest one is
   * usually the root cause rather than a symptom.
   */
  firstDivergence?: ParityDivergence;
}

/** Density at a world position. Injected so this stays pure and testable. */
export type DensityAt = (x: number, y: number, z: number) => number;

function notComparable(
  chunk: Pick<ChunkDataResponse, "chunkX" | "chunkZ">,
  reason: string,
): ChunkParityResult {
  return {
    comparable: false,
    reason,
    chunkX: chunk.chunkX,
    chunkZ: chunk.chunkZ,
    totalVoxels: 0,
    mismatches: 0,
    matchRatio: 0,
    extraSolid: 0,
    extraAir: 0,
  };
}

/**
 * Compare one fetched chunk against local evaluation.
 *
 * Iterates Y outermost and ascending so `firstDivergence` is the lowest
 * disagreement in the chunk, which is deterministic and diagnostically useful.
 */
export function compareChunkSolidity(
  chunk: ChunkDataResponse,
  densityAt: DensityAt,
): ChunkParityResult {
  // The sidecar fabricates a heightmap when a chunk is not on disk yet.
  // Diffing against invented terrain would report nonsense with total
  // confidence, so refuse outright rather than qualify the number.
  if (chunk.dataSource === "synthetic") {
    return notComparable(
      chunk,
      "This chunk has not been generated by the game yet, so there is nothing to compare against. Visit it in-game, let it save, then retry.",
    );
  }

  const { chunkX, chunkZ, sizeX, sizeZ, yMin, yMax, blocks } = chunk;
  const yRange = Math.max(1, yMax - yMin);
  const expected = sizeX * sizeZ * yRange;
  if (!blocks || blocks.length < expected) {
    return notComparable(
      chunk,
      `Chunk data is incomplete (${blocks?.length ?? 0} of ${expected} blocks).`,
    );
  }

  let mismatches = 0;
  let extraSolid = 0;
  let extraAir = 0;
  let firstDivergence: ParityDivergence | undefined;

  for (let y = yMin; y < yMax; y++) {
    const yOffset = y - yMin;
    for (let lz = 0; lz < sizeZ; lz++) {
      const worldZ = chunkZ * sizeZ + lz;
      for (let lx = 0; lx < sizeX; lx++) {
        const worldX = chunkX * sizeX + lx;
        // Layout mirrors the sidecar's encoding, which in turn mirrors
        // worldMeshBuilder: (lz * sizeX + lx) * yRange + (y - yMin).
        const idx = (lz * sizeX + lx) * yRange + yOffset;
        const gameSolid = blocks[idx] !== AIR_BLOCK_ID;

        const density = densityAt(worldX, y, worldZ);
        const localSolid = density > SOLID_THRESHOLD;

        if (gameSolid !== localSolid) {
          mismatches++;
          if (localSolid) extraSolid++;
          else extraAir++;
          if (!firstDivergence) {
            firstDivergence = {
              x: worldX,
              y,
              z: worldZ,
              game: gameSolid ? "solid" : "air",
              local: localSolid ? "solid" : "air",
              density,
            };
          }
        }
      }
    }
  }

  return {
    comparable: true,
    chunkX,
    chunkZ,
    totalVoxels: expected,
    mismatches,
    matchRatio: expected > 0 ? (expected - mismatches) / expected : 0,
    extraSolid,
    extraAir,
    firstDivergence,
  };
}

/** One-line summary for the Bridge readout. Keep it short; this is a status row. */
export function formatParitySummary(r: ChunkParityResult): string {
  if (!r.comparable) return r.reason ?? "Cannot compare this chunk.";
  if (r.mismatches === 0) {
    return `Terrain matches the game exactly (${r.totalVoxels.toLocaleString()} voxels).`;
  }
  const pct = (r.matchRatio * 100).toFixed(2);
  const d = r.firstDivergence;
  const where = d ? ` · lowest at (${d.x}, ${d.y}, ${d.z}), game ${d.game} / preview ${d.local}` : "";
  return `${pct}% match · ${r.mismatches.toLocaleString()} of ${r.totalVoxels.toLocaleString()} voxels differ${where}`;
}
