package com.hypixel.hytale.builtin.hytalegenerator.assets.density;

import com.hypixel.hytale.builtin.hytalegenerator.assets.ThreadBridge;
import com.hypixel.hytale.builtin.hytalegenerator.density.Density;
import com.hypixel.hytale.builtin.hytalegenerator.referencebundle.ReferenceBundle;
import com.hypixel.hytale.builtin.hytalegenerator.rng.SeedBox;
import com.hypixel.hytale.builtin.hytalegenerator.workerindexer.WorkerIndexer;

import org.bson.BsonDocument;
import org.joml.Vector3d;

import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * End-to-end density-graph parity: decode real worldgen JSON with the GAME'S OWN
 * codecs, build the runtime Density, and sample it.
 *
 * This is a stronger check than the per-node harness in Parity.java. That one pins
 * individual primitives; this one pins the whole pipeline — codec field names and
 * defaults, node wiring, seed derivation through SeedBox, and evaluation order — for
 * graphs taken verbatim from shipped assets.
 *
 * Declared inside the density asset package so it can reach DensityAsset.CODEC and
 * the package-private Argument plumbing without reflection.
 *
 * Usage: see graph-parity.sh. Takes a directory of *.json density graphs and emits
 * one JSON fixture with sampled values for each.
 */
public final class GraphParity {

    /** Sample coordinates. Deliberately off-lattice so nothing lands on a cell corner. */
    private static final double[] XS = { -512.5, -100.0, -33.0, 0.0, 17.25, 100.0, 512.5 };
    private static final double[] YS = { -64.0, 0.0, 37.5, 100.0, 210.0 };
    private static final double[] ZS = { -256.25, -7.0, 0.0, 64.5, 300.0 };

    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.err.println("usage: GraphParity <graph-dir> [worldSeed]");
            System.exit(2);
        }
        Path dir = Path.of(args[0]);
        String worldSeed = args.length > 1 ? args[1] : "";

        // Populate the codec type registry. AssetManager's constructor is what calls
        // CODEC.register(...) for every density/material/prop type, so nothing decodes
        // until one has been built. The EventRegistry it wants is only used to hook
        // asset reload events, which never fire here.
        bootstrapCodecRegistry();

        List<Path> files = new ArrayList<>();
        try (var stream = Files.list(dir)) {
            stream.filter(p -> p.toString().endsWith(".json")).sorted().forEach(files::add);
        }

        PrintWriter out = new PrintWriter(System.out);
        out.println("{");
        out.println("\"$comment\": \"Generated by tools/parity/GraphParity.java using the real V2 codecs. Do not hand-edit.\",");
        out.println("\"worldSeed\": " + quote(worldSeed) + ",");
        out.println("\"xs\": " + arr(XS) + ",");
        out.println("\"ys\": " + arr(YS) + ",");
        out.println("\"zs\": " + arr(ZS) + ",");
        out.println("\"graphs\": [");

        boolean first = true;
        for (Path file : files) {
            String name = file.getFileName().toString().replaceAll("\\.json$", "");
            String json = Files.readString(file);

            String error = null;
            StringBuilder values = new StringBuilder();
            try {
                BsonDocument doc = BsonDocument.parse(json);
                DensityAsset asset = DensityAsset.CODEC.decode(doc);
                if (asset == null) throw new IllegalStateException("codec returned null");

                WorkerIndexer indexer = new WorkerIndexer(1);
                DensityAsset.Argument arg = new DensityAsset.Argument(
                        new SeedBox(worldSeed),
                        new ReferenceBundle(),
                        indexer.getWorkedIds().get(0),
                        new ThreadBridge());

                Density density = asset.build(arg);
                Density.Context ctx = new Density.Context();
                ctx.position = new Vector3d();
                ctx.densityAnchor = null;

                for (double x : XS) {
                    for (double y : YS) {
                        for (double z : ZS) {
                            ctx.position.set(x, y, z);
                            append(values, density.process(ctx));
                        }
                    }
                }
            } catch (Throwable t) {
                error = t.getClass().getSimpleName() + ": " + String.valueOf(t.getMessage());
            }

            if (!first) out.println(",");
            first = false;
            out.print("{\"name\": " + quote(name));
            if (error != null) {
                out.print(", \"error\": " + quote(error) + "}");
            } else {
                out.print(", \"values\": [" + values + "]}");
            }
        }

        out.println();
        out.println("]");
        out.println("}");
        out.flush();
    }

    /**
     * Build an AssetManager purely for its side effect of registering every asset
     * type with its codec. Failures are reported rather than thrown so the harness
     * still runs and the fixture records why nothing decoded.
     */
    private static void bootstrapCodecRegistry() {
        try {
            // HytaleAssetStore's static init reads the server's parsed CLI options,
            // which are null outside main(). Parsing an empty argv fills them in with
            // defaults; nothing here touches the network or the filesystem.
            com.hypixel.hytale.server.core.Options.parse(new String[0]);
        } catch (Throwable t) {
            System.err.println("option bootstrap failed: " + t);
        }
        try {
            var eventRegistry = new com.hypixel.hytale.event.EventRegistry(
                    new java.util.ArrayList<>(), () -> false, "parity", null);
            new com.hypixel.hytale.builtin.hytalegenerator.assets.AssetManager(
                    eventRegistry, com.hypixel.hytale.logger.HytaleLogger.getLogger());
        } catch (Throwable t) {
            System.err.println("codec registry bootstrap failed: " + t);
            Throwable cause = t.getCause();
            while (cause != null) {
                System.err.println("  caused by: " + cause);
                for (StackTraceElement el : cause.getStackTrace()) {
                    if (el.getClassName().startsWith("com.hypixel")) {
                        System.err.println("    at " + el);
                        break;
                    }
                }
                cause = cause.getCause();
            }
        }
    }

    private static void append(StringBuilder sb, double d) {
        if (sb.length() > 0) sb.append(',');
        sb.append(num(d));
    }

    private static String num(double d) {
        if (Double.isNaN(d)) return "\"NaN\"";
        if (Double.isInfinite(d)) return d > 0 ? "\"Infinity\"" : "\"-Infinity\"";
        return Double.toString(d);
    }

    private static String arr(double[] values) {
        StringBuilder sb = new StringBuilder();
        for (double v : values) append(sb, v);
        return "[" + sb + "]";
    }

    private static String quote(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }
}
