package com.hypixel.hytale.builtin.hytalegenerator.noise;

import com.hypixel.hytale.builtin.hytalegenerator.rng.SeedBox;

import java.io.PrintWriter;

/**
 * Ground-truth dumper for TerraNova's noise parity tests.
 *
 * Declared in the V2 noise package so it can reach the package-private
 * {@link Simplex} class directly. That lets us pin the two layers separately:
 *
 *   "simplex" — raw Simplex.noise(), validating hytaleNoise.ts (gradients,
 *               permutation table, skew/unskew constants) with no FBM involved.
 *   "cases"   — SimplexNoiseField.valueAt(), validating density/fbm.ts
 *               (seeded per-octave offsets, frequency/amplitude, normalizer).
 *
 * A failure in "simplex" means the core is wrong; a failure only in "cases"
 * means the octave/seed layer is wrong. Without the split, one masks the other.
 *
 * Regenerate with tools/parity/generate.sh — do not run javac by hand.
 */
public final class Parity {

    /** Raw longs: isolates the FBM layer from SeedBox's string hashing. */
    private static final long[] SEEDS = { 0L, 1L, -1L, 12345L, -987654321L };
    private static final int[] OCTAVES = { 1, 2, 3, 6 };
    private static final double[] PERSISTENCE = { 0.5, 0.09, 1.0 };
    private static final double[] LACUNARITY = { 2.0, 6.0, 1.5 };
    private static final double[] SCALE = { 50.0, 350.0 };

    /** Negatives, zero, fractional, and large coordinates. */
    private static final double[] COORDS = { -512.5, -33.0, 0.0, 17.25, 100.0, 4096.0 };

    private static final double[] CELL_SCALES = { 50.0, 120.0 };
    private static final double[] CELL_JITTERS = { 0.3, 1.0 };
    private static final int[] CELL_OCTAVES = { 1, 3 };

    /** Key chains for SeedBox derivation, root first. */
    private static final String[][] SEED_CHAINS = {
        { "MyWorldSeed", "Skyreach_Base_Density" },
        { "MyWorldSeed" },
        { "", "" },
        { "12345", "Skyreach_Caves_Density", "child2" },
        { "Plains1_Oak", "Base-Terrain" },
    };

    public static void main(String[] args) {
        PrintWriter out = new PrintWriter(System.out);
        out.println("{");
        out.println("\"$comment\": \"Generated by tools/parity/Parity.java from the real V2 noise implementation. Do not hand-edit.\",");
        out.println("\"coords\": " + arr(COORDS) + ",");

        // ---- Layer 1: raw simplex, no octaves, no seed ----
        StringBuilder s2 = new StringBuilder();
        StringBuilder s3 = new StringBuilder();
        for (double x : COORDS) {
            for (double z : COORDS) {
                // Raw simplex is sampled at small coordinates: at world scale the
                // lattice aliases and every sample lands near a cell corner.
                append(s2, Simplex.noise(x / 50.0, z / 50.0));
                append(s3, Simplex.noise(x / 50.0, z / 50.0, (x + z) / 100.0));
            }
        }
        out.println("\"simplex2d\": [" + s2 + "],");
        out.println("\"simplex3d\": [" + s3 + "],");

        // ---- Layer 2: the seeded octave field ----
        out.println("\"cases\": [");
        boolean first = true;
        for (long seed : SEEDS) {
            for (int octaves : OCTAVES) {
                for (double persistence : PERSISTENCE) {
                    for (double lacunarity : LACUNARITY) {
                        for (double scale : SCALE) {
                            SimplexNoiseField field = SimplexNoiseField.builder()
                                    .withSeed(seed)
                                    .withNumberOfOctaves(octaves)
                                    .withAmplitudeMultiplier(persistence)
                                    .withFrequencyMultiplier(lacunarity)
                                    .withScale(scale)
                                    .build();

                            StringBuilder v2d = new StringBuilder();
                            for (double x : COORDS) {
                                for (double z : COORDS) append(v2d, field.valueAt(x, z));
                            }
                            StringBuilder v3d = new StringBuilder();
                            for (double v : COORDS) append(v3d, field.valueAt(v, v * 0.5, -v));

                            if (!first) out.println(",");
                            first = false;
                            out.print("{\"seed\":" + seed
                                    + ",\"octaves\":" + octaves
                                    + ",\"persistence\":" + num(persistence)
                                    + ",\"lacunarity\":" + num(lacunarity)
                                    + ",\"scale\":" + num(scale)
                                    + ",\"v2d\":[" + v2d + "]"
                                    + ",\"v3d\":[" + v3d + "]}");
                        }
                    }
                }
            }
        }
        out.println();
        out.println("],");

        // ---- Layer 3: cell noise (FastNoiseLite cellular) ----
        // CellNoise2D/3D expose only ScaleX/Y/Z, Jitter, Octaves, Seed, CellType.
        // There is no Lacunarity, Persistence, ReturnType or DistanceFunction field:
        // CellType IS the CellularReturnType, and the distance function is left at
        // FastNoiseLite's default (EuclideanSq).
        out.println("\"cellCases\": [");
        boolean firstCell = true;
        for (long seed : SEEDS) {
            for (double scale : CELL_SCALES) {
                for (double jitter : CELL_JITTERS) {
                    for (int octaves : CELL_OCTAVES) {
                        for (FastNoiseLite.CellularReturnType cellType : FastNoiseLite.CellularReturnType.values()) {
                            CellNoiseField field = new CellNoiseField(
                                    (int) seed, scale, scale, scale, jitter, octaves, cellType);

                            StringBuilder v2d = new StringBuilder();
                            for (double x : COORDS) {
                                for (double z : COORDS) append(v2d, field.valueAt(x, z));
                            }
                            StringBuilder v3d = new StringBuilder();
                            for (double v : COORDS) append(v3d, field.valueAt(v, v * 0.5, -v));

                            if (!firstCell) out.println(",");
                            firstCell = false;
                            out.print("{\"seed\":" + (int) seed
                                    + ",\"scale\":" + num(scale)
                                    + ",\"jitter\":" + num(jitter)
                                    + ",\"octaves\":" + octaves
                                    + ",\"cellType\":\"" + cellType.name() + "\""
                                    + ",\"v2d\":[" + v2d + "]"
                                    + ",\"v3d\":[" + v3d + "]}");
                        }
                    }
                }
            }
        }
        out.println();
        out.println("],");

        // Defaults are REFLECTED off freshly constructed asset objects rather than
        // transcribed, so a future game update that changes a default fails the test
        // instead of silently drifting.
        out.println("\"defaults\": {");
        String[] assetClasses = {
            "SimplexNoise2dDensityAsset",
            "SimplexNoise3DDensityAsset",
            "CellNoise2DDensityAsset",
            "CellNoise3DDensityAsset",
        };
        for (int i = 0; i < assetClasses.length; i++) {
            out.print("  \"" + assetClasses[i] + "\": " + reflectDefaults(assetClasses[i]));
            out.println(i < assetClasses.length - 1 ? "," : "");
        }
        out.println("},");

        // SeedBox: child() concatenates keys, then FastRandom(fullKey.hashCode()).nextInt().
        out.println("\"seedBox\": [");
        boolean firstSeed = true;
        for (String[] chain : SEED_CHAINS) {
            SeedBox box = new SeedBox(chain[0]);
            for (int i = 1; i < chain.length; i++) box = box.child(chain[i]);
            if (!firstSeed) out.println(",");
            firstSeed = false;
            out.print("{\"chain\":[");
            for (int i = 0; i < chain.length; i++) {
                if (i > 0) out.print(",");
                out.print("\"" + chain[i] + "\"");
            }
            out.print("],\"derived\":" + box.createSupplier().get() + "}");
        }
        out.println();
        out.println("]");
        out.println("}");
        out.flush();
    }

    /**
     * Instantiate a *DensityAsset with its no-arg constructor and dump every
     * declared instance field. Those fields are exactly the JSON defaults: the
     * codec only overwrites a field when the key is present in the asset file.
     */
    private static String reflectDefaults(String simpleName) {
        String fqn = "com.hypixel.hytale.builtin.hytalegenerator.assets.density." + simpleName;
        try {
            Class<?> cls = Class.forName(fqn);
            java.lang.reflect.Constructor<?> ctor = cls.getDeclaredConstructor();
            ctor.setAccessible(true);
            Object instance = ctor.newInstance();

            StringBuilder sb = new StringBuilder("{");
            boolean first = true;
            for (java.lang.reflect.Field f : cls.getDeclaredFields()) {
                if (java.lang.reflect.Modifier.isStatic(f.getModifiers())) continue;
                f.setAccessible(true);
                Object value = f.get(instance);
                if (!first) sb.append(",");
                first = false;
                sb.append("\"").append(f.getName()).append("\":");
                if (value == null) sb.append("null");
                else if (value instanceof Number) sb.append(value.toString());
                else if (value instanceof Boolean) sb.append(value.toString());
                else sb.append("\"").append(value).append("\"");
            }
            return sb.append("}").toString();
        } catch (ReflectiveOperationException e) {
            return "{\"$error\":\"" + e.getClass().getSimpleName() + ": " + e.getMessage() + "\"}";
        }
    }

    private static void append(StringBuilder sb, double d) {
        if (sb.length() > 0) sb.append(',');
        sb.append(num(d));
    }

    /** Double.toString gives the shortest representation that round-trips exactly. */
    private static String num(double d) {
        if (Double.isNaN(d)) return "\"NaN\"";
        if (Double.isInfinite(d)) return d > 0 ? "\"Infinity\"" : "\"-Infinity\"";
        return Double.toString(d);
    }

    private static String arr(double[] values) {
        StringBuilder sb = new StringBuilder();
        for (double v : values) append(sb, v);
        return "[" + sb + "]";
    }
}
