package com.hypixel.hytale.builtin.hytalegenerator.density;

import com.hypixel.hytale.builtin.hytalegenerator.rng.RngField;

import java.io.PrintWriter;

/**
 * Ground-truth dumper for the Update 6 `WhiteNoise` density node.
 *
 * Declared in the V2 density package so it can construct {@link WhiteNoiseDensity}
 * and populate a package-visible {@link Density.Context} directly.
 *
 * Two layers are pinned separately, mirroring Parity.java's split:
 *
 *   "rngField" — RngField.get(x, y, z), the raw positional hash.
 *   "density"  — WhiteNoiseDensity.process(), which is what a graph actually
 *                evaluates and includes whatever scaling sits on top of the hash.
 *
 * A failure only in "density" means the mapping from hash to double is wrong;
 * a failure in "rngField" means the hash itself is.
 *
 * Regenerate with tools/parity/generate-whitenoise.sh — do not run javac by hand.
 */
public final class WhiteNoiseParity {

    private static final int[] SEEDS = { 0, 1, -1, 12345, -987654321 };
    private static final double[] COORDS = { -512.5, -33.0, 0.0, 17.25, 100.0, 4096.0 };

    public static void main(String[] args) {
        PrintWriter out = new PrintWriter(System.out);
        out.println("{");
        out.println("\"$comment\": \"Generated by tools/parity/WhiteNoiseParity.java from the real V2 "
                + "WhiteNoiseDensity. Do not hand-edit.\",");

        out.print("\"coords\": [");
        for (int i = 0; i < COORDS.length; i++) {
            if (i > 0) out.print(",");
            out.print(COORDS[i]);
        }
        out.println("],");

        out.println("\"cases\": [");
        for (int s = 0; s < SEEDS.length; s++) {
            int seed = SEEDS[s];
            RngField field = new RngField(seed);
            WhiteNoiseDensity density = new WhiteNoiseDensity(seed);

            StringBuilder rng = new StringBuilder();
            StringBuilder den = new StringBuilder();
            boolean first = true;
            for (double x : COORDS) {
                for (double y : COORDS) {
                    for (double z : COORDS) {
                        if (!first) { rng.append(","); den.append(","); }
                        first = false;
                        rng.append(field.get(x, y, z));

                        Density.Context ctx = new Density.Context();
                        ctx.position.set(x, y, z);
                        den.append(density.process(ctx));
                    }
                }
            }
            out.print("  {\"seed\": " + seed
                    + ", \"rngField\": [" + rng + "]"
                    + ", \"density\": [" + den + "]}");
            out.println(s == SEEDS.length - 1 ? "" : ",");
        }
        out.println("]");
        out.println("}");
        out.flush();
    }
}
