/**
 * Hytale Update 6's node registry, as the editor's source of truth for what
 * the generator will actually accept.
 *
 * `hytale-update6-schema.json` is generated by
 * `scripts/extract-hytale-schema.mjs` from `AssetManager.java`'s
 * `CODEC.register("Name", …)` calls — the exact set of types the server
 * deserialises — together with each asset's `BuilderCodec` fields. Regenerate
 * it against a new shared-source release rather than editing it by hand.
 *
 * Keys are `Category:Type`. That qualification is load-bearing: 48 type names
 * are registered under more than one category ("Imported" under 19 of them),
 * so a name alone does not identify a type.
 */

import registry from "../data/hytale-update6-schema.json";

export interface Update6Field {
  name: string;
  /** "number" | "integer" | "string" | "boolean" | "color", a category
   *  reference such as "Density", an array of either, or "enum:Owner.Name". */
  type: string;
  required: boolean;
  default?: string | number | boolean | null;
  /** Present when the enum's constants could be resolved from the source. */
  enum?: string[];
}

export interface Update6Type {
  category: string;
  type: string;
  /** The Java asset class, so a reader can go check the original. */
  assetClass: string;
  fields: Update6Field[];
}

interface Registry {
  format: string;
  source: string;
  categories: string[];
  typesByCategory: Record<string, string[]>;
  types: Record<string, Update6Type>;
}

const REGISTRY = registry as unknown as Registry;

export function update6Key(category: string, type: string): string {
  return `${category}:${type}`;
}

/** Whether Update 6's generator will deserialise this type in this category. */
export function isRegisteredType(category: string, type: string): boolean {
  return update6Key(category, type) in REGISTRY.types;
}

export function getUpdate6Type(category: string, type: string): Update6Type | undefined {
  return REGISTRY.types[update6Key(category, type)];
}

export function getUpdate6Field(
  category: string,
  type: string,
  field: string,
): Update6Field | undefined {
  return getUpdate6Type(category, type)?.fields.find((f) => f.name === field);
}

export function update6Categories(): string[] {
  return REGISTRY.categories;
}

export function update6TypesIn(category: string): string[] {
  return REGISTRY.typesByCategory[category] ?? [];
}

export function allUpdate6Keys(): string[] {
  return Object.keys(REGISTRY.types);
}

/**
 * Why a node type the editor offers is absent from the registry.
 *
 * - `registered`  — Update 6 accepts it.
 * - `editor-only` — a TerraNova construct that is never serialised as a node
 *                   (file-level wrappers, and the enum entries the palette
 *                   shows as pickable sub-types).
 * - `legacy`      — was a real type once, but Update 6 will reject it. Kept so
 *                   old graphs still open; hidden from the palette.
 */
export type NodeAvailability = "registered" | "editor-only" | "legacy";

/**
 * Editor-side constructs, listed rather than pattern-matched so that adding one
 * is a deliberate act. `Biome:*` are the file-level wrappers TerraNova edits
 * (a biome document, a world-structure asset); they have no generator codec
 * because they are not nodes.
 */
const EDITOR_ONLY = new Set([
  "Biome:BiomeAsset",
  "Biome:DAOTerrain",
  "Biome:HytaleGenerator",
  "Biome:NoiseRange",
  "Biome:WorldStructureAsset",
  "Biome:WorldStructureNoiseRange",
]);

/**
 * Types Update 6 does not register and that are not editor constructs.
 *
 * Each is here because it was checked against the shipped assets and found
 * absent — not because it merely failed a name lookup.
 */
const LEGACY = new Set([
  // Zero occurrences in HytaleAssets; the shipped documents use the
  // unprefixed "Constant" / "DensityDelimited" that Update 6 registers.
  "EnvironmentProvider:EnvironmentConstant",
  "EnvironmentProvider:EnvironmentDensityDelimited",
  "TintProvider:TintConstant",
  "TintProvider:TintDensityDelimited",
  // Registered under PointGenerator, not PositionProvider.
  "PositionProvider:Mesh",
  // No codec registration under any category.
  "Pattern:Gap",
  "PositionProvider:Positions",
  "Prop:Curve",
  "Prop:UniquePrefab",
]);

/**
 * Classifies a node type the editor offers.
 *
 * `isSubType` marks palette entries that stand for an enum value rather than a
 * node — a CellNoise return type, a distance function — so they are expected to
 * have no registration of their own.
 */
export function nodeAvailability(
  category: string,
  type: string,
  options: { isSubType?: boolean } = {},
): NodeAvailability {
  const key = update6Key(category, type);
  if (isRegisteredType(category, type)) return "registered";
  if (options.isSubType || EDITOR_ONLY.has(key)) return "editor-only";
  if (LEGACY.has(key)) return "legacy";
  // Unclassified and unregistered: treat as legacy so it is surfaced rather
  // than silently offered. Adding it to one of the sets above is the fix.
  return "legacy";
}

/** Registered types that carry no editor definition yet. */
export function unimplementedUpdate6Keys(known: Iterable<string>): string[] {
  const have = new Set(known);
  return allUpdate6Keys().filter((k) => !have.has(k));
}
